household <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", 
                        na.strings = "?", colClasses=c("character", "character", rep("numeric",7)))
household$Date <- as.Date(household$Date, "%d/%m/%Y")
householdfeb <- subset(household, household$Date == "2007-02-01" | household$Date == "2007-02-02")
datetime <- paste(householdfeb$Date, householdfeb$Time)
householdfeb <- cbind(householdfeb, datetime)
householdfeb$datetime <- strptime(householdfeb$datetime, format = "%Y-%m-%d %H:%M:%S")
plot(householdfeb$datetime, householdfeb$Sub_metering_1, ylab = "Energy sub metering", xlab=NA, type="n")
lines(householdfeb$datetime, householdfeb$Sub_metering_1)
lines(householdfeb$datetime, householdfeb$Sub_metering_2, col="red")
lines(householdfeb$datetime, householdfeb$Sub_metering_3, col="blue")
legend('topright', legend = lnames, col = c('black', 'red', 'blue'), lty=1)
dev.copy(png, file="plot3.png")
dev.off()