household <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", 
                        na.strings = "?", colClasses=c("character", "character", rep("numeric",7)))
household$Date <- as.Date(household$Date, "%d/%m/%Y")
householdfeb <- subset(household, household$Date == "2007-02-01" | household$Date == "2007-02-02")
datetime <- paste(householdfeb$Date, householdfeb$Time)
householdfeb <- cbind(householdfeb, datetime)
householdfeb$datetime <- strptime(householdfeb$datetime, format = "%Y-%m-%d %H:%M:%S")
par(mfrow = c(2, 2), mar=c(4,4,3,3), cex.lab = 0.8)
plot(householdfeb$datetime, householdfeb$Global_active_power, ylab = "Global Active Power", xlab=NA, type="n")
lines(householdfeb$datetime, householdfeb$Global_active_power)
plot(householdfeb$datetime, householdfeb$Voltage, ylab = "Voltage", xlab = "datetime", type="n")
lines(householdfeb$datetime, householdfeb$Voltage)
plot(householdfeb$datetime, householdfeb$Sub_metering_1, ylab = "Energy sub metering", xlab=NA, type="n")
lines(householdfeb$datetime, householdfeb$Sub_metering_1)
lines(householdfeb$datetime, householdfeb$Sub_metering_2, col="red")
lines(householdfeb$datetime, householdfeb$Sub_metering_3, col="blue")
legend('topright', legend = lnames, col = c('black', 'red', 'blue'), lty=1, cex = 0.7)
plot(householdfeb$datetime, householdfeb$Global_reactive_power, ylab = "Global_reactive_power", xlab = "datetime", type="n")
lines(householdfeb$datetime, householdfeb$Global_reactive_power)
dev.copy(png, file="plot4.png")
dev.off()